server.port: 7733
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  properties:
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/decision_maker
    username: postgres
    password: admin
